# Civic 89 release identity. SPDX-License-Identifier: GPL-3.0-or-later
set(CIVIC89_VERSION "${PROJECT_VERSION}-dev")
if(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$")
    set(CIVIC89_ARCH arm64)
elseif(CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
    set(CIVIC89_ARCH x64)
else()
    message(FATAL_ERROR "Select x64 or ARM64 through a Civic 89 preset.")
endif()
set(CIVIC89_DIRTY "")
set(CIVIC89_DIRTY_JSON false)
if(EXISTS "${CMAKE_SOURCE_DIR}/.git")
    find_package(Git REQUIRED)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE CIVIC89_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE civic89_changes COMMAND_ERROR_IS_FATAL ANY)
    if(civic89_changes)
        set(CIVIC89_DIRTY " (dirty)")
        set(CIVIC89_DIRTY_JSON true)
    endif()
elseif(EXISTS "${CMAKE_SOURCE_DIR}/source-provenance.json")
    # Never accidentally inherit Git identity from a parent checkout.
    file(READ "${CMAKE_SOURCE_DIR}/source-provenance.json" civic89_source_identity)
    string(JSON CIVIC89_COMMIT GET "${civic89_source_identity}" commit)
    string(JSON civic89_source_version GET "${civic89_source_identity}" version)
    if(NOT civic89_source_version STREQUAL CIVIC89_VERSION)
        message(FATAL_ERROR "Source archive version does not match the project.")
    endif()
    set(CIVIC89_DIRTY " (source archive; modifications untracked)")
    set(CIVIC89_DIRTY_JSON true)
else()
    message(FATAL_ERROR "Use a Git checkout or the corresponding release source ZIP with source-provenance.json.")
endif()
string(LENGTH "${CIVIC89_COMMIT}" civic89_commit_length)
if(NOT civic89_commit_length EQUAL 40 OR NOT CIVIC89_COMMIT MATCHES "^[a-f0-9]+$")
    message(FATAL_ERROR "Invalid source commit identity.")
endif()
string(SUBSTRING "${CIVIC89_COMMIT}" 0 12 CIVIC89_REVISION)
file(READ "${CMAKE_SOURCE_DIR}/vcpkg.json" civic89_manifest)
string(JSON CIVIC89_VCPKG_BASELINE GET "${civic89_manifest}" builtin-baseline)
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")
configure_file("${CMAKE_SOURCE_DIR}/cmake/Civic89BuildInfo.h.in" "${CMAKE_BINARY_DIR}/generated/Civic89BuildInfo.h" @ONLY)
configure_file("${CMAKE_SOURCE_DIR}/packaging/build-info.json.in" "${CMAKE_BINARY_DIR}/build-info.json" @ONLY)
