# Exact application ClCompile list from micropolis-cpp.vcxproj, including presentation and application services.
set(CIVIC89_INHERITED_SOURCES
    src/UiSettings.cpp
    src/OverlayModel.cpp
    src/UI/ModernInterface.cpp
    src/Camera2D.cpp
    src/DisplaySettings.cpp
    src/AudioManager.cpp
    src/DiagnosticLog.cpp
    src/WindowsFileStorage.cpp
    src/RecoveryStore.cpp
    src/EngineState.cpp
    src/EngineServices.cpp
    src/EngineStep.cpp
    src/EngineDigest.cpp
    src/MapRenderer.cpp
    src/SpriteRenderer.cpp
    src/PresentationUtil.cpp
    src/PresentationTools.cpp
    src/Budget.cpp
    src/Connection.cpp
    src/Evaluation.cpp
    src/FileIo.cpp
    src/Font.cpp
    src/GameDataLoader.cpp
    src/Graphics.cpp
    src/g_ani.cpp
    src/main.cpp
    src/Map.cpp
    src/Math/IsZero.cpp
    src/Math/Point.cpp
    src/Math/Rectangle.cpp
    src/Month.cpp
    src/RCI.cpp
    src/Scan.cpp
    src/Sprite.cpp
    src/StringRender.cpp
    src/s_alloc.cpp
    src/s_disast.cpp
    src/s_gen.cpp
    src/s_msg.cpp
    src/Power.cpp
    src/s_sim.cpp
    src/Texture.cpp
    src/ToolActions.cpp
    src/ToolManager.cpp
    src/Traffic.cpp
    src/UI/BudgetWindow.cpp
    src/UI/DashboardWindow.cpp
    src/UI/EvaluationWindow.cpp
    src/UI/FileIoDialog.cpp
    src/UI/GraphWindow.cpp
    src/UI/InterfaceManager.cpp
    src/UI/MiniMapWindow.cpp
    src/UI/OptionsWindow.cpp
    src/UI/QueryWindow.cpp
    src/UI/ToolPalette.cpp
    src/UI/WindowBase.cpp
    src/UI/WindowGroup.cpp
    src/UI/WindowStack.cpp
    src/Util.cpp
    src/w_resrc.cpp
    src/w_sound.cpp
    src/w_tk.cpp
    src/w_update.cpp
    src/Zone.cpp
)
