if(NOT SOURCE_DIR OR NOT DESTINATION)
    message(FATAL_ERROR "Pass SOURCE_DIR and DESTINATION to stage runtime files.")
endif()
file(READ "${SOURCE_DIR}/assets/runtime-assets.json" inventory)
string(JSON embedded_count LENGTH "${inventory}" embedded_files)
math(EXPR embedded_last "${embedded_count} - 1")
foreach(index RANGE ${embedded_last})
    string(JSON path GET "${inventory}" embedded_files ${index} path)
    string(JSON expected GET "${inventory}" embedded_files ${index} sha256)
    file(SHA256 "${SOURCE_DIR}/${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Embedded asset checksum mismatch: ${path}.")
    endif()
endforeach()
string(JSON count LENGTH "${inventory}" files)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    string(JSON path GET "${inventory}" files ${index} path)
    string(JSON expected GET "${inventory}" files ${index} sha256)
    string(JSON hash_mode GET "${inventory}" files ${index} hash_mode)
    if(hash_mode STREQUAL "lf")
        file(READ "${SOURCE_DIR}/${path}" content)
        string(REPLACE "\r\n" "\n" content "${content}")
        string(SHA256 actual "${content}")
    else()
        file(SHA256 "${SOURCE_DIR}/${path}" actual)
    endif()
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Runtime asset checksum mismatch: ${path}. Review and update the inventory intentionally.")
    endif()
    get_filename_component(directory "${DESTINATION}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${SOURCE_DIR}/${path}" "${DESTINATION}/${path}" ONLY_IF_DIFFERENT)
endforeach()
foreach(path IN ITEMS COPYING __README_OG README.md NOTICE.md AUTHORS.md assets/runtime-assets.json assets/ASSET-LICENSES.yml
    project/reference/RUNTIME_ASSETS.md project/reference/README_SDLPP.md project/reference/UPSTREAMS.md
    project/BUILDING.md project/RELEASING.md project/CLASSIC_COMPATIBILITY.md project/ENHANCED_CITY_FORMAT.md
    PROJECT_STATUS.md packaging/release-gates.json
    project/engineering/08_ROADMAP_AND_IMPLEMENTATION_BACKLOG.md tests/baseline/M5_UI_CITY.png
    tools/release/ReleaseCommon.ps1 tools/release/Update-Portable.ps1 tools/release/Launch-Portable.ps1)
    get_filename_component(directory "${DESTINATION}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${SOURCE_DIR}/${path}" "${DESTINATION}/${path}" ONLY_IF_DIFFERENT)
endforeach()
if(VCPKG_SHARE_DIR)
    file(GLOB copyrights "${VCPKG_SHARE_DIR}/*/copyright")
    foreach(path IN LISTS copyrights)
        get_filename_component(directory "${path}" DIRECTORY)
        get_filename_component(package "${directory}" NAME)
        file(MAKE_DIRECTORY "${DESTINATION}/licenses/dependencies/${package}")
        file(COPY_FILE "${path}" "${DESTINATION}/licenses/dependencies/${package}/copyright" ONLY_IF_DIFFERENT)
    endforeach()
endif()
message(STATUS "Staged ${count} inventoried assets in ${DESTINATION}")
