include("${SOURCE_DIR}/cmake/InheritedSources.cmake")
file(READ "${SOURCE_DIR}/micropolis-cpp.vcxproj" project)
string(REGEX MATCHALL "<ClCompile Include=\"[^\"]+\"" matches "${project}")
set(inherited)
foreach(match IN LISTS matches)
    string(REGEX REPLACE "<ClCompile Include=\"([^\"]+)\"" "\\1" path "${match}")
    string(REPLACE "\\" "/" path "${path}")
    list(APPEND inherited "${path}")
endforeach()
list(SORT inherited)
list(SORT CIVIC89_INHERITED_SOURCES)
if(NOT inherited STREQUAL CIVIC89_INHERITED_SOURCES)
    message(FATAL_ERROR "The CMake and inherited Visual Studio source lists differ.")
endif()
list(LENGTH inherited count)
message(STATUS "All ${count} inherited translation units match CMake.")
