# Preserve the audited simulation/data inputs without needing .git in source exports.
# SPDX-License-Identifier: GPL-3.0-or-later
file(STRINGS "${SOURCE_DIR}/tests/fixtures/m8-fidelity-source-manifest.txt" entries)
set(count 0)
foreach(entry IN LISTS entries)
    if(entry MATCHES "^#" OR entry STREQUAL "")
        continue()
    endif()
    if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
        message(FATAL_ERROR "Invalid fidelity manifest entry: ${entry}")
    endif()
    set(expected "${CMAKE_MATCH_1}")
    set(path "${CMAKE_MATCH_2}")
    # Git/archive/Windows checkouts can use different text line endings.
    if(path MATCHES "\\.(cpp|h|json)$")
        file(READ "${SOURCE_DIR}/${path}" content)
        string(REPLACE "\r\n" "\n" content "${content}")
        string(SHA256 actual "${content}")
    else()
        file(SHA256 "${SOURCE_DIR}/${path}" actual)
    endif()
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Audited gameplay input changed: ${path}. Review fidelity before updating this reference.")
    endif()
    math(EXPR count "${count}+1")
endforeach()
if(count LESS 40)
    message(FATAL_ERROR "Incomplete fidelity source/data contract")
endif()
message(STATUS "${count} audited gameplay source/data inputs match the fidelity contract.")
