include("${SOURCE_DIR}/cmake/EngineSources.cmake")
# Walk local includes as well as translation units: a clean source file can
# still import SDL or application state transitively through an old header.
set(pending ${CIVIC89_ENGINE_SOURCES})
set(visited)
while(pending)
    list(POP_FRONT pending path)
    if(path IN_LIST visited)
        continue()
    endif()
    list(APPEND visited "${path}")
    file(READ "${SOURCE_DIR}/${path}" source)
    if(source MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(SDL|[Ww]indows\\.h|Texture\\.h|main\\.h|UI/|GameDataLoader)")
        message(FATAL_ERROR "Engine imports presentation/platform code: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*\"[^\"]+\"" includes "${source}")
    get_filename_component(directory "${path}" DIRECTORY)
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*\"([^\"]+)\"" "\\1" header "${include}")
        cmake_path(SET resolved NORMALIZE "${directory}/${header}")
        if(EXISTS "${SOURCE_DIR}/${resolved}")
            list(APPEND pending "${resolved}")
        endif()
    endforeach()
endwhile()
# Check direct imports. CRT/Windows transitively load system window libraries;
# those are not application dependencies and must not cause a false failure.
execute_process(COMMAND "${DUMP_TOOL}" /dump /dependents "${RUNNER}"
    RESULT_VARIABLE result OUTPUT_VARIABLE imports ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect runner imports: ${errors}")
endif()
string(TOLOWER "${imports}" imports)
if(imports MATCHES "sdl[^ \n]*\\.dll|user32\\.dll|gdi32\\.dll")
    message(FATAL_ERROR "Runner directly imports graphics/window runtime: ${imports}")
endif()
list(LENGTH visited count)
message(STATUS "Engine boundary verified across ${count} sources/headers and runner imports.")
